spring.application.name=malune

spring.datasource.url=jdbc:postgresql://pg-2255cb81-dev-1701.e.aivencloud.com:19573/malune?sslmode=require
spring.datasource.username=adm_malune
spring.datasource.password=malune@26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true